#!/bin/sh
set -e

cat <<EOF > /repo/apps/frontend/public/env-config-dev.js
window.__ENV__ = {
  AUTH0_DOMAIN: "${AUTH0_DOMAIN}",
  AUTH0_CLIENT_ID: "${AUTH0_CLIENT_ID}",
  AUTH0_AUDIENCE: "${AUTH0_AUDIENCE}",
  BASE_URL: "${BASE_URL}",
  SERVER_NAME: "${SERVER_NAME}",
  VITE_APP_SERVER: "${APP_SERVER}",
  VITE_BASE_URL: "${VITE_BASE_URL}",
  VITE_AUTH0_AUDIENCE: "${VITE_AUTH0_AUDIENCE}",
  VITE_AUTH0_CLIENT_ID: "${VITE_AUTH0_CLIENT_ID}",
  VITE_AUTH0_DOMAIN: "${VITE_AUTH0_DOMAIN}",
  VITE_AUTH0_REDIRECT_URI: "${VITE_AUTH0_REDIRECT_URI}",
  VITE_AUTH0_LOGOUT_REDIRECT_URI: "${VITE_AUTH0_LOGOUT_REDIRECT_URI}",
  VITE_AUTH0_SCOPE: "${VITE_AUTH0_SCOPE}",
  VITE_AUTH0_CACHE_LOCATION: "${VITE_AUTH0_CACHE_LOCATION}",
  VITE_AUTH0_USE_REFRESH_TOKENS: "${VITE_AUTH0_USE_REFRESH_TOKENS:-false}",
  VITE_AUTH0_USE_REFRESH_TOKENS_FALLBACK: "${VITE_AUTH0_USE_REFRESH_TOKENS_FALLBACK:-false}",
  VITE_AUTH0_ORGANIZATION: "${VITE_AUTH0_ORGANIZATION}",
  VITE_AUTH0_ORGANIZATION_NAME: "${VITE_AUTH0_ORGANIZATION_NAME}",
  VITE_AUTH0_ORGANIZATION_LOGO: "${VITE_AUTH0_ORGANIZATION_LOGO}",
  VITE_AUTH0_ORGANIZATION_ENABLED: "${VITE_AUTH0_ORGANIZATION_ENABLED:-false}",
  VITE_AUTH0_ORGANIZATION_DEFAULT: "${VITE_AUTH0_ORGANIZATION_DEFAULT}",
  VITE_AUTH0_ORGANIZATION_DEFAULT_NAME: "${VITE_AUTH0_ORGANIZATION_DEFAULT_NAME}",
  VITE_AUTH0_ORGANIZATION_DEFAULT_LOGO: "${VITE_AUTH0_ORGANIZATION_DEFAULT_LOGO}"
};
EOF
