services:
  mongo:
    image: mongo:7
    container_name: mongo_dev
    command: ["--replSet","rs0","--bind_ip_all","--keyFile","/etc/mongo-keyfile"]
    ports: ["27019:27017"]             # host:27019 -> contenedor:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=pgaisse
      - MONGO_INITDB_ROOT_PASSWORD=Patoch-2202
      - MONGO_INITDB_DATABASE=productionDB
    volumes:
      - mongo_dev_data:/data/db
      - ../mongo/keys/mongo-keyfile:/etc/mongo-keyfile:ro
      - ./../mongo/init-user.sh:/docker-entrypoint-initdb.d/01-init-user.sh:ro
      # ⚠️ Mueve el restore a un job separado (ver abajo)
      # - ./../mongo/dev-init/01-init-restore.sh:/docker-entrypoint-initdb.d/02-restore.sh:ro
      - /home/appointment-platform/mongo-backup:/backup_dev
    healthcheck:
      test: ["CMD","mongosh","--quiet",
             "--username=pgaisse","--password=Patoch-2202","--authenticationDatabase=admin",
             "--eval","db.runCommand({ ping: 1 }).ok"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks: [app_network_dev]

  mongo-init-replica:
    image: mongo:7
    depends_on:
      mongo:
        condition: service_healthy
    restart: "no"
    environment:
      MONGO_INITDB_ROOT_USERNAME: pgaisse
      MONGO_INITDB_ROOT_PASSWORD: Patoch-2202
    entrypoint: ["/bin/bash","-lc"]
    command: |
      echo "⏳ Esperando ping..."
      for i in {1..60}; do
        mongosh --host mongo:27017 --quiet --eval "db.runCommand({ ping: 1 }).ok" && break || sleep 2
      done
      echo "🚀 rs.initiate() autenticado"
      mongosh --host mongo:27017 -u "$MONGO_INITDB_ROOT_USERNAME" -p "$MONGO_INITDB_ROOT_PASSWORD" --authenticationDatabase admin --quiet --eval '
        try {
          rs.initiate({_id:"rs0", members:[{_id:0, host:"mongo:27017"}]})
        } catch(e) { print(e.message) }
      '
      echo "⏳ Esperando PRIMARY..."
      for i in {1..60}; do
        state=$(mongosh --host mongo:27017 -u "$MONGO_INITDB_ROOT_USERNAME" -p "$MONGO_INITDB_ROOT_PASSWORD" --authenticationDatabase admin --quiet --eval 'var m=rs.status().members.find(x=>x.self); m?m.stateStr:""')
        [ "$state" = "PRIMARY" ] && echo "✅ PRIMARY" && exit 0 || sleep 2
      done
      echo "❌ No se alcanzó PRIMARY"; exit 1
    networks: [app_network_dev]

  # (Opcional) job de restore DESPUÉS de tener PRIMARY
  mongo-restore:
    image: mongo:7
    depends_on:
      mongo-init-replica:
        condition: service_completed_successfully
    volumes:
      - /home/appointment-platform/mongo-backup:/backup_dev
    entrypoint: ["/bin/bash","-lc"]
    command: |
      echo "♻️ Restaurando backup..."
      mongorestore --host mongo:27017 -u pgaisse -p 'Patoch-2202' --authenticationDatabase admin --drop /backup_dev/productionDB || exit 1
      echo "✅ Restore listo"
    networks: [app_network_dev]


  backend:
    image: node:20-alpine
    container_name: backend_dev
    working_dir: /repo/apps/backend
    command: sh -lc "npm install --no-audit --no-fund && npm run dev"
    env_file:
      - ../../apps/backend/.env.backend.dev

    expose:
      - "3003"
      - "3001"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ../..:/repo
      - /repo/apps/backend/node_modules
    depends_on:
      mongo:
        condition: service_healthy
      mongo-init-replica:
        condition: service_completed_successfully
    networks:
      - app_network_dev

  frontend:
    image: node:20-alpine
    container_name: frontend_dev
    working_dir: /repo/apps/frontend
    command: sh -lc "CHOKIDAR_USEPOLLING=true WATCHPACK_POLLING=true npm install --no-audit --no-fund && npm run dev -- --host 0.0.0.0 --port 3004"
    env_file:
      - ../../apps/frontend/.env.frontend.dev
    depends_on:
      - backend
    expose:
      - "3000"
      - "3004"
    volumes:
      - ../..:/repo
      - /repo/apps/frontend/node_modules
    networks:
      - app_network_dev

  nginx:
    container_name: nginx_dev
    image: nginx:1.27-alpine
    ports:
      - "8080:80"
      - "8443:8443"
    env_file:
      - ../../apps/backend/.env.backend.dev
    volumes:
      - ../nginx/nginx.dev.conf:/etc/nginx/conf.d/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - app_network_dev
    depends_on:
      - backend
      - frontend

  certbot:
    image: certbot/certbot
    container_name: certbot_dev
    volumes:
      - appointment_dev_certbot_www:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - app_network_dev

volumes:
  mongo_dev_data:
  appointment_dev_certbot_www:
  letsencrypt_dev:

networks:
  app_network_dev:
    driver: bridge
