name: dev
services:
  mongo:
    image: mongo:7
    container_name: mongo_dev
    ports:
      - "27019:27017"
    env_file:
      - ../../apps/backend/.env.backend.dev
    logging:
      driver: "json-file"
      options:
        max-size: "10m"     # tamaño máximo de un archivo de log
        max-file: "3"       # número de archivos de log rotados
    environment:
      - MONGO_INITDB_ROOT_USERNAME=pgaisse
      - MONGO_INITDB_ROOT_PASSWORD=Patoch-2202
      - MONGO_INITDB_DATABASE=productionDB
    volumes:
      - mongo_dev_data:/data/db
      - ./../mongo/init-user.sh:/docker-entrypoint-initdb.d/init-user.sh:ro
      - /home/appointment-platform/mongo-backup:/backup_dev
      - ./../mongo/dev-init/01-init-restore.sh:/docker-entrypoint-initdb.d/init-restore-dev.sh:ro
   
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 }).ok"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app_network_dev

  backend:
    image: node:20-alpine
    container_name: backend_dev
    working_dir: /repo/apps/backend
    command: sh -lc "npm install --no-audit --no-fund && npm run dev"
    env_file:
      - ../../apps/backend/.env.backend.dev
    logging:
      driver: "json-file"
      options:
        max-size: "10m"     # tamaño máximo de un archivo de log
        max-file: "3"       # número de archivos de log rotados
    expose:
      - "3003"
    volumes:
      - ../..:/repo
      - /repo/apps/backend/node_modules
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - app_network_dev

  frontend:
    image: node:20-alpine
    container_name: frontend_dev
    working_dir: /repo/apps/frontend
    command: sh -lc "CHOKIDAR_USEPOLLING=true WATCHPACK_POLLING=true npm install --no-audit --no-fund && npm run dev -- --host 0.0.0.0 --port 3004"
    env_file:
      - ../../apps/frontend/.env.frontend.dev
    logging:
      driver: "json-file"
      options:
        max-size: "10m"     # tamaño máximo de un archivo de log
        max-file: "3"       # número de archivos de log rotados
    expose:
      - "3004"
    volumes:
      - ../..:/repo
      - /repo/apps/frontend/node_modules
    depends_on:
      - backend
      
    networks:
      - app_network_dev

  nginx:
    container_name: nginx_dev
    image: nginx:1.27-alpine
    ports:
      - "8080:80"
      - "8443:443"
    env_file:
      - ../../apps/backend/.env.backend.dev
    logging:
      driver: "json-file"
      options:
        max-size: "10m"     # tamaño máximo de un archivo de log
        max-file: "3"       # número de archivos de log rotados
    volumes:
      - ../nginx/nginx.dev.conf:/etc/nginx/conf.d/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - app_network_dev
    depends_on:
      - backend
      - frontend

  certbot:
    image: certbot/certbot
    container_name: certbot_dev
    logging:
      driver: "json-file"
      options:
        max-size: "10m"     # tamaño máximo de un archivo de log
        max-file: "3"       # número de archivos de log rotados
    volumes:
      - appointment_dev_certbot_www:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - app_network_dev

volumes:
  mongo_dev_data:
  appointment_dev_certbot_www:
  letsencrypt_dev:

networks:
  app_network_dev:
    driver: bridge
