FROM node:20-alpine AS build
WORKDIR /app
COPY apps/frontend/package*.json ./
RUN npm ci
COPY apps/frontend ./
COPY .env.frontend.prod ./
RUN npm run build

FROM nginx:stable-alpine
RUN apk add --no-cache certbot certbot-nginx
COPY infra/nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80 443
