FROM node:20-alpine as build
WORKDIR /app

# Instalar dependencias
COPY apps/frontend/package*.json ./
RUN npm install

# Copiar código y compilar
COPY apps/frontend ./
RUN npm run build

# Imagen de producción con Nginx
FROM nginx:1.28-alpine

# Copiar build
COPY --from=build /app/dist /usr/share/nginx/html
COPY infra/nginx/nginx.conf /etc/nginx/conf.d/default.conf

# Inyectar el script de variables en index.html
RUN sed -i 's|<script type="module"|<script src="/env-config.js"></script>\n    <script type="module"|' /usr/share/nginx/html/index.html

# Copiar script de configuración dinámica
COPY apps/frontend/env-config.sh /docker-entrypoint.d/env-config.sh
RUN chmod +x /docker-entrypoint.d/env-config.sh

EXPOSE 80
