FROM node:20-alpine as build
WORKDIR /app


# Instalar dependencias
COPY apps/frontend/package*.json ./
RUN npm install

# Copiar código y compilar
COPY apps/frontend ./
RUN npm run build


# Imagen de producción con Nginx
FROM nginx:1.28-alpine

# Copiar build del frontend
COPY --from=build /app/dist /usr/share/nginx/html

# Copiar script de configuración dinámica

# Inyectar script de variables dinámicas


EXPOSE 80 443