# .github/workflows/build-backend.yml
name: Build & Push Backend

on:
  push:
    branches: [ "main" ]
    paths:
      - 'apps/backend/**'
      - 'infra/docker/Dockerfile.backend'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: infra/docker/Dockerfile.backend
          push: true
          tags: ghcr.io/YOUR_NS/iconicsmiles-backend:main
